
package:
  name: transferservice

server:
  port: 8080

spring:
  aop:
    auto: true
  profiles:
    active: DEV

management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: always

ledger:
  service:
    endpoint:
      baseUrl: https://api-prod:8443
      path: /ledger/transfer

logging:
  level:
    root: INFO
    za.co.sanlam: INFO
  file:
    name: logs/ledger-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

